name: Elmo Rise
source: https://knowyourmeme.com/memes/elmo-rise
keywords:
  - elmo
  - fire
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.05
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - when you vibe coded too hard and your api keys are somehow on reddit
